spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: SAMPLE
    password: 1234
    url: jdbc:mariadb://np.developerjini.com:3306/springboot_db
  jpa:
    show-sql: true
